---

  - name: Install dos2unix
    yum:
      name: dos2unix
      state: latest

  - name: Change file
    command: dos2unix /root/demo/dump/config

#Install Router and Message Processor
  - name: Install Router and Message Processor on nodes 2 
    command: 'sudo bash /opt/apigee/apigee-setup/bin/setup.sh -p rmp -f /root/demo/dump/config'
    tags: ['rmp']
   

  
