---
  - name: Install dos2unix
    yum:
      name: dos2unix
      state: latest

  - name: Change file
    command: dos2unix /root/demo/dump/config

  - name: Install Datastore cluster on nodes 1
    command: 'sudo bash /opt/apigee/apigee-setup/bin/setup.sh -p ds -f /root/demo/dump/config'
    tags: ['ds']
   
    