---


  - name: Install Datastore cluster on nodes 1
    command: 'sudo bash /opt/apigee/apigee-setup/bin/setup.sh -p ds -f /root/demo/dump/config.txt'
    tags: ['ds']
    when: ds

 
#Install Management Server 

  - name: Install Management Server on node 1
    command: 'sudo bash /opt/apigee/apigee-setup/bin/setup.sh -p ms -f /root/demo/dump/config.txt'
    tags: ['ms']
    when: ms

#Restart edge 

  - name: Restart Edge UI after installation
    command: /opt/apigee/apigee-service/bin/apigee-service edge-ui restart
    tags: ['restart']
    