---


   #Install Management Server 

  - name: Install Management Server on node 1
    command: 'sudo bash /opt/apigee/apigee-setup/bin/setup.sh -p ms -f /root/demo/dump/config.txt'
    tags: ['ms']
    
    